### ISSUE TITLE
error editing record 262 in b2share production

### ISSUE THREAD

**Issue by llehtine** [EUDAT-B2SHARE/b2share#809] opened 2015-11-19 14:55 UTC
Hi,

When trying to access https://b2share.eudat.eu/b2deposit/262/edit, it will 500 Internal Server Error. This is what I get on log files:

```
2015-11-19 16:50:23,055 ERROR:  [in /var/www/.virtualenvs/b2share/lib/python2.7/site-packages/invenio-2.0.7.dev20150901-py2.7.egg/invenio/ext/logging/wrappers.py:310]
Traceback (most recent call last):
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/invenio-2.0.7.dev20150901-py2.7.egg/invenio/ext/legacy/__init__.py", line 124, in __call__
    response = self.app.full_dispatch_request()
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/flask_restful/__init__.py", line 258, in error_router
    return original_handler(e)
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/invenio-2.0.7.dev20150901-py2.7.egg/invenio/base/wrappers.py", line 125, in handle_user_exception
    return super(Flask, self).handle_user_exception(e)
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/flask_login.py", line 658, in decorated_view
    return func(*args, **kwargs)
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/invenio-2.0.7.dev20150901-py2.7.egg/invenio/b2share/modules/b2deposit/views.py", line 89, in edit
    return edt.get_page(int(recid))
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/invenio-2.0.7.dev20150901-py2.7.egg/invenio/b2share/modules/b2deposit/edit.py", line 44, in get_page
    domain=metaclass, getattr=getattr)
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/invenio-2.0.7.dev20150901-py2.7.egg/invenio/b2share/modules/b2deposit/templates/b2share-edit.html", line 3, in top-level template code
    {% from "b2share-addmeta-table.html" import deposit_fieldsets, deposit_js_fixes with context %}
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/jinja2/environment.py", line 1013, in make_module
    return TemplateModule(self, self.new_context(vars, shared, locals))
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/jinja2/environment.py", line 1070, in __init__
    self._body_stream = list(template.root_render_func(context))
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/invenio-2.0.7.dev20150901-py2.7.egg/invenio/b2share/modules/b2deposit/templates/b2share-addmeta-table.html", line 197, in top-level template code
    {{ deposit_fieldsets() }}
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/invenio-2.0.7.dev20150901-py2.7.egg/invenio/b2share/modules/b2deposit/templates/b2share-addmeta-table.html", line 46, in template
    {{ meta_field(getattr(form, f)) }}
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/invenio-2.0.7.dev20150901-py2.7.egg/invenio/b2share/modules/b2deposit/templates/b2share-addmeta-table.html", line 23, in template
    <td>{{f(**kwargs)|safe}}</td>
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/wtforms/fields/core.py", line 149, in __call__
    return self.meta.render_field(self, kwargs)
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/wtforms/meta.py", line 53, in render_field
    return field.widget(field, **render_kw)
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/wtforms/widgets/core.py", line 257, in __call__
    escape(text_type(field._value()), quote=False)
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/wtforms/fields/core.py", line 529, in _value
    return text_type(self.data) if self.data is not None else ''
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 163: ordinal not in range(128)
2015-11-19 16:50:23,329 ERROR: Exception on /b2deposit/262/edit [GET] [in /var/www/.virtualenvs/b2share/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/invenio-2.0.7.dev20150901-py2.7.egg/invenio/ext/legacy/__init__.py", line 124, in __call__
    response = self.app.full_dispatch_request()
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/flask_restful/__init__.py", line 258, in error_router
    return original_handler(e)
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/invenio-2.0.7.dev20150901-py2.7.egg/invenio/base/wrappers.py", line 125, in handle_user_exception
    return super(Flask, self).handle_user_exception(e)
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/flask_login.py", line 658, in decorated_view
    return func(*args, **kwargs)
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/invenio-2.0.7.dev20150901-py2.7.egg/invenio/b2share/modules/b2deposit/views.py", line 89, in edit
    return edt.get_page(int(recid))
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/invenio-2.0.7.dev20150901-py2.7.egg/invenio/b2share/modules/b2deposit/edit.py", line 44, in get_page
    domain=metaclass, getattr=getattr)
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/invenio-2.0.7.dev20150901-py2.7.egg/invenio/b2share/modules/b2deposit/templates/b2share-edit.html", line 3, in top-level template code
    {% from "b2share-addmeta-table.html" import deposit_fieldsets, deposit_js_fixes with context %}
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/jinja2/environment.py", line 1013, in make_module
    return TemplateModule(self, self.new_context(vars, shared, locals))
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/jinja2/environment.py", line 1070, in __init__
    self._body_stream = list(template.root_render_func(context))
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/invenio-2.0.7.dev20150901-py2.7.egg/invenio/b2share/modules/b2deposit/templates/b2share-addmeta-table.html", line 197, in top-level template code
    {{ deposit_fieldsets() }}
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/invenio-2.0.7.dev20150901-py2.7.egg/invenio/b2share/modules/b2deposit/templates/b2share-addmeta-table.html", line 46, in template
    {{ meta_field(getattr(form, f)) }}
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/invenio-2.0.7.dev20150901-py2.7.egg/invenio/b2share/modules/b2deposit/templates/b2share-addmeta-table.html", line 23, in template
    <td>{{f(**kwargs)|safe}}</td>
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/wtforms/fields/core.py", line 149, in __call__
    return self.meta.render_field(self, kwargs)
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/wtforms/meta.py", line 53, in render_field
    return field.widget(field, **render_kw)
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/wtforms/widgets/core.py", line 257, in __call__
    escape(text_type(field._value()), quote=False)
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/wtforms/fields/core.py", line 529, in _value
    return text_type(self.data) if self.data is not None else ''
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 163: ordinal not in range(128)
```

**Comment by emanueldima** [comment] 2015-11-23 08:34
When viewing the same record, the metadata fields do not render at all, probably because of the same error.

The description field of the record contains at position 163 a slightly more unusual Unicode character (RIGHT SINGLE QUOTATION MARK, encoded in utf-8 as 0xE2 0x80 0x99), and that is probably what triggers the error. However, it's not the text but the code that should be modified.

**Comment by cjhak** [comment] 2015-12-01 07:02
Reported via RT: https://helpdesk.eudat.eu/Ticket/Display.html?id=10432

**Comment by cjhak** [comment] 2015-12-01 07:12
@llehtine, @emanueldima, any idea when and how this can be fixed so I can inform the requestor in helpdesk?

**Comment by llehtine** [comment] 2015-12-01 10:16
The record mentioned in ticket is now fixed (removed the illegal character), but I'll leave this open as the issue is still in the code.

**Comment by janiheikkinen** [comment] 2016-06-03 07:48
Is this also taken into account in the [B2SHARE 2.0 milestone](https://github.com/EUDAT-B2SHARE/b2share/milestones/B2SHARE%202.0)?

**Comment by emanueldima** [comment] 2016-06-03 07:57
Yes, this issue is solved in v2, as it only uses python 3 which by default uses utf-8 for strings.

**Comment by emanueldima** [comment] 2017-01-10 14:34
won't fix in v1, not reproducible in v2

**Closed by emanueldima** 2017-01-10 14:34 UTC
