### ISSUE TITLE
Bibupload fails on empty files

### ISSUE THREAD

**Issue by llehtine** [EUDAT-B2SHARE/b2share#575] opened 2015-02-24 08:45 UTC
Rest API seems to be allow uploading of 0-byte sized files. However, bibupload can't progress them, so that will but the bibsched in "manual mode" and doesen't allow any more uploads to be progressed (and won't progress the deposit with has 0-byte file either).

This is what is coming to logfile in bibsched:

2015-02-24 10:41:34 --> Input file '/var/www/.virtualenvs/b2share/var/tmp-shared/webdeposit_2015-02-24_10:41:28jAFkRu.marcxml', input mode 'replace'.
2015-02-24 10:41:35 --> Error in downloading '/powerfolder/ss-next/74af2848bc0011e49282005056941346/test.txt_dd18bf3a8e0a2a3e53e2661c7fb53534.txt' because of: Impossible to copy the local file '/powerfolder/ss-next/74af2848bc0011e49282005056941346/test.txt_dd18bf3a8e0a2a3e53e2661c7fb53534.txt': /powerfolder/ss-next/74af2848bc0011e49282005056941346/test.txt_dd18bf3a8e0a2a3e53e2661c7fb53534.txt seems to be empty

**Comment by llehtine** [comment] 2015-02-24 11:46
User is reporting, that he was also able to upload 0-byte file through the web-interface

**Comment by emanueldima** [comment] 2015-02-24 11:59
Can you find out the brower used? In Chrome and Firefox it shouldn't happen.

**Comment by llehtine** [comment] 2015-02-24 12:08
From the log-files: "Mozilla/5.0 (X11; Linux x86_64; rv:19.0) Gecko/20100101 Firefox/19.0"

**Comment by emanueldima** [comment] 2015-02-27 13:20
Just for the record: The ideal solution for the users is to allow them to upload 0-length files, with the appropriate UI warnings. Currently we cannot do that because bibupload fails on empty files with an error message of form `Impossible to copy the local file ... seems to be empty` (see `invenio/legacy/bibdocfile/api.py:3787, fn: download_local_file`). We could remove this check, but other services (indexing, searching) might also crash on empty files and give us trouble in production. Is anyone willing to change and test this?

**Comment by emanueldima** [comment] 2015-06-01 10:43
For the moment we cannot allow the upload of empty files from the UI, because this is not properly implemented in plupload (see https://github.com/moxiecode/plupload/issues/1172; uploading empty files seems to crash IE10: https://github.com/moxiecode/plupload/blob/764bb47f136a3e427a9f3e2ce2319516aded8e7f/js/moxie.js#L3422) 

But the REST API should allow this functionality, so we should just fix bibupload.

**Comment by emanueldima** [comment] 2015-06-01 10:46
@nharraud I'm assigning this to you, as it is related to invenio.

**Comment by nharraud** [comment] 2015-06-05 11:45
I can reproduce this on Invenio branch maint-2.0. I also found the lines explicitly forbidding empty files upload in bibdocfile module. Replacing these exceptions with warnings seems to work at first sight but I still have some errors in the logs.
```
2015-06-04 16:16:01 --> /Users/nharraud/.virtualenvs/invenio-maint-2.0/var/data/deposit/storage/17/db7b9351-5451-4501-a2a7-505fb1473891-empty-file.txt seems to be empty
Traceback (most recent call last):
  File "/Users/nharraud/.virtualenvs/invenio-maint-2.0/src/invenio/invenio/legacy/bibupload/engine.py", line 2036, in elaborate_fft_tags
    bibdoc = bibrecdocs.get_bibdoc(docname)
  File "/Users/nharraud/.virtualenvs/invenio-maint-2.0/src/invenio/invenio/legacy/bibdocfile/api.py", line 1072, in get_bibdoc
    " docname '%s'" % (self.id, docname)
InvenioBibDocFileError: Recid '9' is not connected with  docname 'db7b9351-5451-4501-a2a7-505fb1473891-empty-file'
2015-06-04 16:16:01 --> /Users/nharraud/.virtualenvs/invenio-maint-2.0/var/data/deposit/storage/17/50ea6e32-74c5-41d6-acc7-e590baa5a6e0-empty-picture.jpg seems to be empty
Traceback (most recent call last):
  File "/Users/nharraud/.virtualenvs/invenio-maint-2.0/src/invenio/invenio/legacy/bibupload/engine.py", line 2036, in elaborate_fft_tags
    bibdoc = bibrecdocs.get_bibdoc(docname)
  File "/Users/nharraud/.virtualenvs/invenio-maint-2.0/src/invenio/invenio/legacy/bibdocfile/api.py", line 1072, in get_bibdoc
    " docname '%s'" % (self.id, docname)
InvenioBibDocFileError: Recid '9' is not connected with  docname '50ea6e32-74c5-41d6-acc7-e590baa5a6e0-empty-picture'
```

This will require to update all the tests for file upload/processing/get in order to be sure that everything works correctly. After that the fix will have to be merged from Invenio to B2Share. If we have only one user complaining about it maybe this feature can wait until we have split B2Share and Invenio. It will be easier and less risky then. What do you think @llehtine @emanueldima ?

**Comment by cjhak** [comment] 2015-06-05 12:32
I see not urgency in this issue rigth now, so postponing to milestone 2.0.

**Comment by emanueldima** [comment] 2015-06-05 13:43
I agree, but then I will change the REST API to reject empty files until this will be fixed.

**Comment by nharraud** [comment] 2016-08-30 14:58
This is closed as we won't fix that for B2Share V1 and B2Share v2 will support empty files without Bibupload.

**Closed by nharraud** 2016-08-30 14:58 UTC
Labels: Bug, Invenio
