### ISSUE TITLE
Doc rest-api: make clear that access_token is server-dependent

### ISSUE THREAD

**Issue by NelsonPereira1991** [EUDAT-B2SHARE/b2share#1391] opened 2017-02-23 10:53 UTC
Hi i'm creating a NodeJS wrapper(https://www.npmjs.com/package/node-b2share-v2) for your EUDAT B2Share V2 API(https://b2share.eudat.eu/help/api).

It is being developed in the context of the DataPublication@UPorto data pilot.

I'm having a few problems when creating a draft. How do I know the respective ID from the draft that was just created? The request is being executed as a POST and following the  $HOSTNAME/api/records/?access_token=$ACCESS_TOKEN url as well with metadata info for the draft following the {"titles":[{"title":"TestRest"}], "community":"e9b9792e-79fb-4b07-b6b4-b9c2bd06d095", "open_access":true, "community_specific": {}} convention. Shouldn't I just receive the info from the created draft ? Instead this is the data I receive, info from records and drafts that are not mine: 
{
  "aggregations": {
    "type": {
      "buckets": [], 
      "doc_count_error_upper_bound": 0, 
      "sum_other_doc_count": 0
    }
  }, 
  "hits": {
    "hits": [
      {
        "created": "2017-02-22T15:06:18.201565+00:00", 
        "files": [
          {
            "bucket": "cafb4f47-117b-4f6e-acbf-7c12e9d8b171", 
            "checksum": "md5:4b05b53a59d616a41b41075435d5d2a9", 
            "ePIC_PID": "http://hdl.handle.net/11304/9bac6018-44b6-4c44-944e-96e5942ab8b1", 
            "key": "NL.HGN.02.LHZ.D.2017.021", 
            "size": 207872, 
            "version_id": "084dd00e-4c4c-418a-9710-06e5706d4749"
          }, 
          {
            "bucket": "cafb4f47-117b-4f6e-acbf-7c12e9d8b171", 
            "checksum": "md5:caf3416386dbf2290972003749f994e2", 
            "ePIC_PID": "http://hdl.handle.net/11304/1327b346-465e-4dd7-8a79-a4ae42fcda45", 
            "key": "NL.HGN.02.LHZ.D.2017.022", 
            "size": 212480, 
            "version_id": "0a84159b-4f04-47fc-8c0c-8375592d8486"
          }, 
          {
            "bucket": "cafb4f47-117b-4f6e-acbf-7c12e9d8b171", 
            "checksum": "md5:737294e8f40e87a864cbb04a13193453", 
            "ePIC_PID": "http://hdl.handle.net/11304/436a9fcf-cf8b-4787-baef-1042cfd6125f", 
            "key": "NL.HGN.02.LHZ.D.2017.023", 
            "size": 202752, 
            "version_id": "8c46d8fb-3247-49c2-be87-61a6ddf36983"
          }
        ], 
        "id": "88b4eb778741411b8c987ef9d8335597", 
        "links": {
          "files": "https://trng-b2share.eudat.eu/api/files/cafb4f47-117b-4f6e-acbf-7c12e9d8b171", 
          "self": "https://trng-b2share.eudat.eu/api/records/88b4eb778741411b8c987ef9d8335597"
        }, 
        "metadata": {
          "$schema": "https://trng-b2share.eudat.eu/api/communities/e9b9792e-79fb-4b07-b6b4-b9c2bd06d095/schemas/0#/json_schema", 
          "DOI": "http://doi.org/10.5072/b2share.88b4eb778741411b8c987ef9d8335597", 
          "community": "e9b9792e-79fb-4b07-b6b4-b9c2bd06d095", 
          "community_specific": {}, 
          "descriptions": [
            {
              "description": "Data for the WFCatalog Collector Demo", 
              "description_type": "Abstract"
            }
          ], 
          "ePIC_PID": "http://hdl.handle.net/11304/22c46716-0beb-4721-9a78-787be683a612", 
          "open_access": true, 
          "owners": [
            26
          ], 
          "publication_state": "published", 
          "titles": [
            {
              "title": "WFCatalog Collector Demo"
            }
          ]
        }, 
        "updated": "2017-02-22T15:06:18.201574+00:00"
      }, 
      {
        "created": "2017-02-22T12:59:23.725576+00:00", 
        "files": [
          {
            "bucket": "64aa3a15-73e2-48a7-84b9-002f3978205e", 
            "checksum": "md5:05402dece72a9abd1d68ba0a70121db0", 
            "ePIC_PID": "http://hdl.handle.net/11304/bc9a98d8-52b3-453b-bb6b-2961a92010ec", 
            "key": "text.txt", 
            "size": 1724, 
            "version_id": "2b4c39cb-14ee-4a93-9ff8-ba6e3f75c82a"
          }
        ], 
        "id": "b044c43a53a0488daa7b05242b8821c9", 
        "links": {
          "files": "https://trng-b2share.eudat.eu/api/files/64aa3a15-73e2-48a7-84b9-002f3978205e", 
          "self": "https://trng-b2share.eudat.eu/api/records/b044c43a53a0488daa7b05242b8821c9"
        }, 
        "metadata": {
          "$schema": "https://trng-b2share.eudat.eu/api/communities/e9b9792e-79fb-4b07-b6b4-b9c2bd06d095/schemas/0#/json_schema", 
          "DOI": "http://doi.org/10.5072/b2share.b044c43a53a0488daa7b05242b8821c9", 
          "community": "e9b9792e-79fb-4b07-b6b4-b9c2bd06d095", 
          "community_specific": {}, 
          "creators": [
            {
              "creator_name": "Alexandr Chernov"
            }
          ], 
          "descriptions": [
            {
              "description": "Sample data for Stanford Parser (demo)", 
              "description_type": "Abstract"
            }
          ], 
          "ePIC_PID": "http://hdl.handle.net/11304/0591b2ed-d5c6-4007-bb99-6b473f3f07fb", 
          "open_access": true, 
          "owners": [
            26
          ], 
          "publication_state": "published", 
          "titles": [
            {
              "title": "Sample data for Stanford Parser"
            }
          ]
        }, 
        "updated": "2017-02-22T12:59:23.725585+00:00"
      }, 
      {
        "created": "2017-02-22T12:46:09.776812+00:00", 
        "files": [], 
        "id": "6e0c9638581e4c3c8f65fbf3490d73a5", 
        "links": {
          "self": "https://trng-b2share.eudat.eu/api/records/6e0c9638581e4c3c8f65fbf3490d73a5"
        }, 
        "metadata": {
          "$schema": "https://trng-b2share.eudat.eu/api/communities/e9b9792e-79fb-4b07-b6b4-b9c2bd06d095/schemas/0#/json_schema", 
          "DOI": "http://doi.org/10.5072/b2share.6e0c9638581e4c3c8f65fbf3490d73a5", 
          "community": "e9b9792e-79fb-4b07-b6b4-b9c2bd06d095", 
          "community_specific": {}, 
          "ePIC_PID": "http://hdl.handle.net/11304/02bd95d0-7f74-4215-8a90-e8ce8aa7b85e", 
          "open_access": true, 
          "owners": [
            8
          ], 
          "publication_state": "published", 
          "titles": [
            {
              "title": "test"
            }
          ]
        }, 
        "updated": "2017-02-22T12:46:09.776822+00:00"
      }, 
      {
        "created": "2017-02-22T11:41:38.053570+00:00", 
        "files": [
          {
            "bucket": "73cb40d4-cf45-46c6-bd8c-8e8d44bfdad4", 
            "checksum": "md5:05402dece72a9abd1d68ba0a70121db0", 
            "key": "text.txt", 
            "size": 1724, 
            "version_id": "fd3f1cab-7ef8-4467-8af4-fd62f4c2dd1b"
          }
        ], 
        "id": "ee984afb81de44fa9cdac1e0cd2372a3", 
        "links": {
          "files": "https://trng-b2share.eudat.eu/api/files/73cb40d4-cf45-46c6-bd8c-8e8d44bfdad4", 
          "self": "https://trng-b2share.eudat.eu/api/records/ee984afb81de44fa9cdac1e0cd2372a3"
        }, 
        "metadata": {
          "$schema": "https://trng-b2share.eudat.eu/api/communities/e9b9792e-79fb-4b07-b6b4-b9c2bd06d095/schemas/0#/json_schema", 
          "community": "e9b9792e-79fb-4b07-b6b4-b9c2bd06d095", 
          "community_specific": {}, 
          "descriptions": [
            {
              "description": "Sample text for the demo", 
              "description_type": "Abstract"
            }
          ], 
          "open_access": true, 
          "owners": [
            26
          ], 
          "publication_state": "published", 
          "titles": [
            {
              "title": "English text for the Stanford Parser"
            }
          ]
        }, 
        "updated": "2017-02-22T11:41:38.053579+00:00"
      }, 
      {
        "created": "2017-02-21T11:33:24.560109+00:00", 
        "files": [
          {
            "bucket": "1d49616d-ee4d-4a68-8c78-d00b7687ba9e", 
            "checksum": "md5:bfa822e19b3d5adb2cd9a37dcbd33c63", 
            "key": "helium berilium test phrase.txt", 
            "size": 53, 
            "version_id": "b065de45-da73-4ac3-a493-feb680b907ce"
          }
        ], 
        "id": "8829680f2cb14d188a9de454df93ba89", 
        "links": {
          "files": "https://trng-b2share.eudat.eu/api/files/1d49616d-ee4d-4a68-8c78-d00b7687ba9e", 
          "self": "https://trng-b2share.eudat.eu/api/records/8829680f2cb14d188a9de454df93ba89"
        }, 
        "metadata": {
          "$schema": "https://trng-b2share.eudat.eu/api/communities/e9b9792e-79fb-4b07-b6b4-b9c2bd06d095/schemas/0#/json_schema", 
          "community": "e9b9792e-79fb-4b07-b6b4-b9c2bd06d095", 
          "community_specific": {}, 
          "open_access": true, 
          "owners": [
            8
          ], 
          "publication_state": "published", 
          "titles": [
            {
              "title": "test"
            }
          ]
        }, 
        "updated": "2017-02-21T11:33:24.560118+00:00"
      }, 
      {
        "created": "2017-02-20T16:10:03.639649+00:00", 
        "files": [
          {
            "bucket": "6e9d3767-4756-44a5-8256-2471e5e78b54", 
            "checksum": "md5:924a47bdfbc387ee4ca585c9dc40b43d", 
            "ePIC_PID": "http://hdl.handle.net/11304/fd8c9729-97ab-47ee-898e-c87bb905b17c", 
            "key": "testdata.txt", 
            "size": 43, 
            "version_id": "30ff750a-1855-4a9c-9220-c1486c998cba"
          }
        ], 
        "id": "f24085fb121b41eabcb7013da2ba7d73", 
        "links": {
          "files": "https://trng-b2share.eudat.eu/api/files/6e9d3767-4756-44a5-8256-2471e5e78b54", 
          "self": "https://trng-b2share.eudat.eu/api/records/f24085fb121b41eabcb7013da2ba7d73"
        }, 
        "metadata": {
          "$schema": "https://trng-b2share.eudat.eu/api/communities/867c4e67-9227-4b6f-8595-c97d37e9de61/schemas/0#/json_schema", 
          "community": "867c4e67-9227-4b6f-8595-c97d37e9de61", 
          "community_specific": {
            "e06cafbc-0598-4dd8-9029-9bf1f74d8b2e": {
              "country": "The Netherlands", 
              "gbif_id": "None", 
              "status": "Awaiting publication", 
              "version_number": "0.1"
            }
          }, 
          "contact_email": "r.m.de.jong@library.leidenuniv.nl", 
          "creators": [
            {
              "creator_name": "Rutger de Jong"
            }
          ], 
          "descriptions": [
            {
              "description": "A number of plants that attacked me in our home.", 
              "description_type": "Abstract"
            }
          ], 
          "disciplines": [
            "3.1.20 \u2192 Biology \u2192 Linnaean taxonomy"
          ], 
          "ePIC_PID": "http://hdl.handle.net/11304/af7c6b6d-c21c-4131-a661-d890d5de9589", 
          "keywords": [
            "plant science"
          ], 
          "license": {
            "license": "Creative Commons Attribution (CC-BY)", 
            "license_uri": "http://creativecommons.org/licenses/by/4.0/"
          }, 
          "open_access": true, 
          "owners": [
            22
          ], 
          "publication_date": "2099-01-01", 
          "publication_state": "published", 
          "titles": [
            {
              "title": "Carnivorous plants"
            }
          ]
        }, 
        "updated": "2017-02-20T16:10:03.639658+00:00"
      }, 
      {
        "created": "2017-02-20T16:09:54.703001+00:00", 
        "files": [
          {
            "bucket": "b5451ba6-a36c-49f0-87cd-6ad9fd3a7fab", 
            "checksum": "md5:a18dab76f9e32d0a4b2e4b4ec31a8cd7", 
            "ePIC_PID": "http://hdl.handle.net/11304/6c91d966-f9e4-4a51-8064-b628ca41b3d2", 
            "key": "metadata.csv", 
            "size": 12719, 
            "version_id": "7562a2bc-bb05-4f65-bec5-20e9066ce047"
          }
        ], 
        "id": "e6d222a8c2924da290f2439aa99ab5c5", 
        "links": {
          "files": "https://trng-b2share.eudat.eu/api/files/b5451ba6-a36c-49f0-87cd-6ad9fd3a7fab", 
          "self": "https://trng-b2share.eudat.eu/api/records/e6d222a8c2924da290f2439aa99ab5c5"
        }, 
        "metadata": {
          "$schema": "https://trng-b2share.eudat.eu/api/communities/e9b9792e-79fb-4b07-b6b4-b9c2bd06d095/schemas/0#/json_schema", 
          "alternate_identifiers": [
            {
              "alternate_identifier": "https://dspace-cris.4science.it/handle/123456789/7", 
              "alternate_identifier_type": "URI"
            }
          ], 
          "community": "e9b9792e-79fb-4b07-b6b4-b9c2bd06d095", 
          "community_specific": {}, 
          "contributors": [
            {
              "contributor_name": "Grenz, Daryl", 
              "contributor_type": "Distributor"
            }
          ], 
          "descriptions": [
            {
              "description": "something", 
              "description_type": "Other"
            }
          ], 
          "ePIC_PID": "http://hdl.handle.net/11304/6466f0da-8847-464d-a836-da368db8d391", 
          "open_access": true, 
          "owners": [
            21
          ], 
          "publication_state": "published", 
          "resource_types": [
            {
              "resource_type_general": "Dataset"
            }
          ], 
          "titles": [
            {
              "title": "metadata"
            }
          ]
        }, 
        "updated": "2017-02-20T16:09:54.703010+00:00"
      }, 
      {
        "created": "2017-02-20T16:09:14.434861+00:00", 
        "files": [
          {
            "bucket": "9e315015-e3e0-4af7-84b9-ef30d31e9645", 
            "checksum": "md5:3481ea4e49246a981ebeb9b2bf3dc145", 
            "ePIC_PID": "http://hdl.handle.net/11304/c2d3aec7-98ee-48e1-a2a2-22c2c0e4a2e7", 
            "key": "result_2016-07-11.csv", 
            "size": 299175, 
            "version_id": "84dacf20-9aa3-4db1-8c51-a70388e7afa3"
          }
        ], 
        "id": "4dd5ac320eee4207a1fecdbe57ded31e", 
        "links": {
          "files": "https://trng-b2share.eudat.eu/api/files/9e315015-e3e0-4af7-84b9-ef30d31e9645", 
          "self": "https://trng-b2share.eudat.eu/api/records/4dd5ac320eee4207a1fecdbe57ded31e"
        }, 
        "metadata": {
          "$schema": "https://trng-b2share.eudat.eu/api/communities/e9b9792e-79fb-4b07-b6b4-b9c2bd06d095/schemas/0#/json_schema", 
          "community": "e9b9792e-79fb-4b07-b6b4-b9c2bd06d095", 
          "community_specific": {}, 
          "contact_email": "up200403800@fe.up.pt", 
          "creators": [
            {
              "creator_name": "up200403800"
            }
          ], 
          "descriptions": [
            {
              "description": "File name holds temporal information.\ndBdata files: contains gathered tweets, inferred language and their corresponding cluster identifier", 
              "description_type": "TechnicalInfo"
            }
          ], 
          "disciplines": [
            "5.3.10.1 \u2192 Information systems \u2192 Management information systems"
          ], 
          "ePIC_PID": "http://hdl.handle.net/11304/59fd6f02-c9ac-46b6-905e-098f7cfa295c", 
          "keywords": [
            "cluster"
          ], 
          "license": {
            "license": "Creative Commons Attribution (CC-BY)", 
            "license_uri": "http://creativecommons.org/licenses/by/4.0/"
          }, 
          "open_access": true, 
          "owners": [
            23
          ], 
          "publication_state": "published", 
          "titles": [
            {
              "title": "tweeprofile"
            }
          ]
        }, 
        "updated": "2017-02-20T16:09:14.434871+00:00"
      }, 
      {
        "created": "2017-02-20T16:00:25.608072+00:00", 
        "id": "a11736ab1b174028a1bbedea63e84411", 
        "links": {
          "files": "https://trng-b2share.eudat.eu/api/files/21786db5-1855-4add-ab50-d377e0a24384", 
          "self": "https://trng-b2share.eudat.eu/api/records/a11736ab1b174028a1bbedea63e84411"
        }, 
        "metadata": {
          "$schema": "https://trng-b2share.eudat.eu/api/communities/e9b9792e-79fb-4b07-b6b4-b9c2bd06d095/schemas/0#/json_schema", 
          "community": "e9b9792e-79fb-4b07-b6b4-b9c2bd06d095", 
          "community_specific": {}, 
          "contact_email": "test@gmail.com", 
          "creators": [
            {
              "creator_name": "Tester Test"
            }
          ], 
          "descriptions": [
            {
              "description": "test test test", 
              "description_type": "Abstract"
            }
          ], 
          "disciplines": [
            "1.1.4 \u2192 Human history \u2192 History of Australia|Australian History"
          ], 
          "ePIC_PID": "http://hdl.handle.net/11304/18ca9dde-c89e-462b-8930-fdcc5dbab2e6", 
          "embargo_date": "2017-08-25T14:53:51.349Z", 
          "keywords": [
            "keyword 1 keyword 2 keyword 3"
          ], 
          "license": {
            "license": "Public Domain Dedication (CC Zero)", 
            "license_uri": "http://creativecommons.org/publicdomain/zero/1.0/"
          }, 
          "open_access": false, 
          "owners": [
            20
          ], 
          "publication_date": "2107", 
          "publication_state": "published", 
          "titles": [
            {
              "title": "Test Data"
            }
          ]
        }, 
        "updated": "2017-02-20T16:00:25.608081+00:00"
      }, 
      {
        "created": "2017-02-17T17:05:06.063639+00:00", 
        "files": [
          {
            "bucket": "5de77341-bb8a-4686-8a38-6ff59b11493c", 
            "checksum": "md5:20b11aa63dec733e1c87592a704634e0", 
            "ePIC_PID": "http://hdl.handle.net/11304/5a896f1d-136b-484a-adf0-f2e8bed92d54", 
            "key": "20160205_B2SHARE API training_Hakansson.pptx", 
            "size": 3516060, 
            "version_id": "55b660d5-57da-467c-8f54-14f188e06f75"
          }
        ], 
        "id": "7dce88c2101a454dbd07221b70ebe715", 
        "links": {
          "files": "https://trng-b2share.eudat.eu/api/files/5de77341-bb8a-4686-8a38-6ff59b11493c", 
          "self": "https://trng-b2share.eudat.eu/api/records/7dce88c2101a454dbd07221b70ebe715"
        }, 
        "metadata": {
          "$schema": "https://trng-b2share.eudat.eu/api/communities/e9b9792e-79fb-4b07-b6b4-b9c2bd06d095/schemas/0#/json_schema", 
          "community": "e9b9792e-79fb-4b07-b6b4-b9c2bd06d095", 
          "community_specific": {}, 
          "ePIC_PID": "http://hdl.handle.net/11304/0f849c38-8bba-4943-8cd1-e2a544fe1456", 
          "open_access": true, 
          "owners": [
            18
          ], 
          "publication_state": "published", 
          "titles": [
            {
              "title": "mstest"
            }
          ]
        }, 
        "updated": "2017-02-17T17:05:06.063656+00:00"
      }
    ], 
    "total": 57
  }, 
  "links": {
    "next": "https://trng-b2share.eudat.eu/api/records/?sort=mostrecent&q=&size=10&page=2", 
    "self": "https://trng-b2share.eudat.eu/api/records/?sort=mostrecent&q=&size=10&page=1"
  }
}

The draft I created is not shown, am I doing something wrong ?

**Comment by nharraud** [comment] 2017-02-28 10:27
Hi @NelsonPereira1991,
First thank you for the integration work you are doing.

The result you are getting looks like a search query. Search queries are performed on the same endpoint but with a GET instead of a POST.
`GET $HOSTNAME/api/records/?access_token=$ACCESS_TOKEN` -> search
`POST $HOSTNAME/api/records/?access_token=$ACCESS_TOKEN` -> create a draft and returns the draft data with a self link pointing to the new draft (`HOSTNAME/api/records/<ID>/draft`).

Is it possible that your code is doing a GET instead of a POST?

**Comment by emanueldima** [comment] 2017-03-01 10:34
It's possible this is caused by a missing trailing slash, see https://github.com/EUDAT-B2SHARE/b2share/issues/1380. A POST request to a url without the final `/` will be answered with a redirect to the correct url (with the final `/`), and the clients usually automatically repeat the initial request to the new address, but using a GET instead of a POST. In this way the request seems to fail and get the list of records instead.

**Comment by NelsonPereira1991** [comment] 2017-03-02 10:17
Hi @emanueldima and @nharraud, sorry for the late reply. Yes by adding the final "/" I no longer receive the result of a search query. However now I get a unauthorized response.

I tried doing a curl with the request too:

curl -i -H "Content-Type:application/json" -d '{"titles":[{"title":"TestRest"}], "community":"e9b9792e-79fb-4b07-b6b4-b9c2bd06d095", "open_access":true, "community_specific": {}}' -X POST https://trng-b2share.eudat.eu/api/records/?access_token=myaccess_token_goes_here

Here is a screenshot with the response I get:

![response](https://cloud.githubusercontent.com/assets/6686528/23502735/c03254dc-ff30-11e6-8122-7e730575f018.png)

I'm using the training url to develop the wrapper, and I created the token here:

![tokens](https://cloud.githubusercontent.com/assets/6686528/23502826/2256af32-ff31-11e6-9240-550a3841c43e.png)

Is the token i'm using not valid for the training url?

**Comment by emanueldima** [comment] 2017-03-02 10:27
Hi Nelson, this should indeed work. I've just tried and works for my user account. Please check that you're using an access_token created on the same trng server (each server has its own authentication, so a token from b2share would not work on trng-b2share). If it still won't work please try with a newly created access token.

**Comment by NelsonPereira1991** [comment] 2017-03-02 10:34
@emanueldima, yes that solved it :D. Previously I had created the token on the main B2share webpage and thought it was valid token in the context of the training site. Sorry for bothering you with such a silly mistake on my part, thanks for the quick reply ;)

**Comment by emanueldima** [comment] 2017-03-02 10:45
Glad to be of help. This is actually a common problem and should be better described in the documentation, so I'll transform this issue in a documentation issue.

**Comment by hevp** [comment] 2019-02-21 15:52
This has been addressed in the API docs: https://eudat.eu/services/userdoc/the-b2share-http-rest-api#Creating_an_access_token

**Closed by hevp** 2019-02-21 15:52 UTC
Labels: Docs, Size: beginner-friendly
