### ISSUE TITLE
UI: authors not displayed on the published record page

### ISSUE THREAD

**Issue by nharraud** [EUDAT-B2SHARE/b2share#1198] opened 2016-11-15 13:01 UTC
**Problem:**
The "authors" are present inside the metadata returned by the backend but the frontend does not display them.

**Comment by emanueldima** [comment] 2016-11-21 11:35
The UI seems to work correctly: https://vm0045.kaj.pouta.csc.fi/records/1033083fedf4408fb5611f23527a926d. I think the issue is that the migrator does not yet converts the authors.

**Comment by emanueldima** [comment] 2016-12-15 15:45
migrator code fixed in https://github.com/EUDAT-B2SHARE/b2share/pull/1227

**Closed by emanueldima** 2016-12-15 15:45 UTC
Labels: Bug, Important, Size: easy, UI, Urgent
