### ISSUE TITLE
account activation is not working

### ISSUE THREAD

**Issue by llehtine** [EUDAT-B2SHARE/b2share#437] opened 2014-09-30 13:36 UTC
When trying to make new account on test/prod and activating the account, it will create the account and send you mail, but clicking the activation will cause message "The authorization token is invalid. "

**Comment by llehtine** [comment] 2015-03-05 16:28
I've now analyzed this and it seems to be due to two things:

1) User-registration in new version of Invenio is bit broken. In the old version, user-creation was done like this:

   uid = run_sql("INSERT INTO user (nickname, email, password, note, settings, last_login) "
        "VALUES (%s,%s,AES_ENCRYPT(email,%s),%s,%s, NOW())",

but in the new one:

   user = User(nickname=nickname,
                email=email,
                password=passw,
                note=activated)

so it will not actually update the last_login time -> last_login time will be the database default. So when the user is created, the last_login is set to 1900-01-01 00:00:00 (well, the user isn't logged in yet, so it should matter, right?)

2) On the prod-server, the garbage collector was set to be bit aggressive (running every 5mins, now changed to 24hours). And when it run, it also cleans the user-table like this:

  ## 5b - delete expired not confirmed email address
    write_message("""DELETE FROM user WHERE note='2' AND NOW()>ADDTIME(last_login, '%s 0:0:0')""" % CFG_WEBSESSION_NOT_CONFIRMED_EMAIL_ADDRESS_EXPIRE_IN_DAYS, verbose=9)
    delcount['email_addresses'] = run_sql("""DELETE FROM user WHERE note='2' AND NOW()>ADDTIME(last_login, '%s 0:0:0')""", (CFG_WEBSESSION_NOT_CONFIRMED_EMAIL_ADDRESS_EXPIRE_IN_DAYS,))

But when the last_login is set to start of 1900-century, it will always succeed deleting the non-confirmed users. So when you sum it up, you would have up to 5 minutes to authorize your email-address, otherwise it would be gone from the user-table, and the mail-cookie link would fail.

I guess this more Invenio-issue also to fix up the user-registering process to set something to last_login when the user is created.

**Comment by jirikuncar** [comment] 2015-03-06 08:43
It has been fixed in Invenio 2.0.0 release.

**Comment by cjhak** [comment] 2015-04-28 12:09
I've tested and verified that account creation works as intended on test-eudatis, but can't test completely for this issue. Moving to milestone 1.4.1, but perhaps this issue can be closed?

**Comment by llehtine** [comment] 2015-04-28 13:31
i think this can be closed yes

**Closed** 2015-04-28 13:36 UTC
Labels: Bug, Deployment, Important
