### ISSUE TITLE
bibindex giving integrity errors to log files

### ISSUE THREAD

**Issue by llehtine** [EUDAT-B2SHARE/b2share#638] opened 2015-05-07 09:24 UTC
Bibindex is generating errors like this to log files:

```
2015-05-06 19:01:08 --> 
Traceback (most recent call last):
  File "/var/www/.virtualenvs/b2share/src/b2share/invenio/legacy/bibindex/engine.py", line 733, in put_word_into_db
    run_sql("INSERT INTO %s (term, hitlist) VALUES (%%s, %%s)" % wash_table_column_name(self.table_name), (word, set.fastdump())) # kwalitee: disable=sql
  File "/var/www/.virtualenvs/b2share/src/b2share/invenio/legacy/dbquery_mysql.py", line 268, in run_sql
    rc = cur.execute(sql, param)
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
IntegrityError: (1062, "Duplicate entry '' for key 'term'")
2015-05-06 19:01:08 --> /var/www/.virtualenvs/b2share/src/b2share/invenio/legacy/dbquery_mysql.py:268: Warning: Incorrect string value: '\xE2, Giu...' for column 'term' at row 1
  rc = cur.execute(sql, param)
```

**Comment by llehtine** [comment] 2015-05-07 09:48
this actually seems to relate: https://github.com/EUDAT-B2SHARE/b2share/issues/99

**Comment by dblommesteijn** [comment] 2015-05-07 10:06
@llehtine if you post your log in trippel back-ticks ` it's easier to see the log.

**Comment by llehtine** [comment] 2015-05-07 10:10
updated

**Comment by cjhak** [comment] 2015-05-07 10:36
Initiated by https://helpdesk.eudat.eu/Ticket/Display.html?id=10341. End user reports search issue for recent deposits.

Indeed, when I test search I get no hits either for the most recent deposits, neither on prod or test-eudatis.

**Comment by llehtine** [comment] 2015-05-07 10:48
On production i've tested, that the 185 is latest one which you can search with search options, and you can see the newer ones if you are giving to search-string the full string of authors, for example: https://b2share.eudat.eu/search?f=author&p=Nagham%20Salman%20%28BSC%29%2C%20Riina%20Salmivalli%20%28CSC%29%2C%20Mark%20Sawyer%20%28EPCC%29%2C%20David%20Manset%20%28MaatG%29%2C%20Adam%20Carter%20%28EPCC%29&ln=en

**Comment by emanueldima** [comment] 2015-05-12 08:42
@jirikuncar @lnielsen Do you have any idea about this?

**Comment by tiborsimko** [comment] 2015-05-20 12:50
Here are a few tips on how to debug this kind of situation.

**1.** Firstly, please make sure that your indexes are well consistent by running a check on them:

```
$ bibsched stop
$ bibindex -u admin -k
[...] Task #32 submitted.
$ bibindex 32
```

If there is something wrong reported back, you can try to repair the affected indexes by following the BibIndex Admin Guide.

**2.** Secondly, the reported error says that the indexer wants to push a new term '' (perhaps coming from `'\xE2, Giu...`) into the tables, while there is already an entry.  The indexer should have noticed that this is an update, not an insert.  If it did not, then this may be due to suspicious accents.  Please check whether you use UTF-8 database encoding and with which collation, for example:

```
$ inveniocfg --detect-system-details
>>> Going to detect system details...
* Hostname: pcuds06
* Invenio version: 1.2.0.19-94763
* Python version: 2.7.9 (default, Mar  1 2015, 12:57:24)  [GCC 4.9.2]
* Apache version: Apache/2.4.10 (Debian) [/usr/sbin/apache2]
* MySQLdb version: 1.2.5
* MySQL version:
    - version: 5.5.43-0+deb8u1
    - character_set_client: utf8
    - character_set_connection: utf8
    - character_set_database: utf8
    - character_set_results: utf8
    - character_set_server: latin1
    - character_set_system: utf8
    - collation_connection: utf8_general_ci
    - collation_database: utf8_general_ci
    - collation_server: latin1_swedish_ci
>>> System details detected successfully.
```

**3.** Thirdly, it is now time to identify which record causes this problem, and which index is affected.  You can launch a new indexing job with the verbose option:

```
$ bibindex -u admin -v 9
```

and observe its log files.  There you should see which index table is affected and which record ID causes this problem.  You can then check the (3a) given record to see whether it is well UTF-8 formatted, and (3b) given table to see which other records are already referring to this term.  It will be easier to provide literal hints after I see the output of the verbose indexing job.

**4.** Fourthly, if you don't want to dive into debugging this incremental indexing problem, please note that you have always a solution of going for full reindexing.  There are not many records present on the B2SHARE instance, so this will be quick.  You can simply launch:

```
$ bibindex -u admin -R
```

which will delete existing index entries and proceeds to re-indexing everything from scratch.

**5.** Last but not least, does @nharraud have access to your running instance? If so, it may be perhaps easier to debug this situation remotely from here?  Please let us know if you'd like to proceed in this way.

**Comment by nharraud** [comment] 2015-05-21 08:13
@cjhak The documents listed by the customers are apparently not searchable because of #652.
I tried to search for them with `title:...` on the production instance and it worked.
I indexed one of the documents in my dev environment and did not have any bibindex error.
Starting the Bibindex process for the global index and reindexing everything as suggested by @tiborsimko would be the easiest way to fix those non-searchable documents.

I am still trying to reproduce the current issue (error during bibindex). @llehtine can you please provide the document which was indexed when the error was logged? Or if you have some logs before and after the lines you copied, it might give us additional clues. And the database's tables encoding too.

**Comment by llehtine** [comment] 2015-05-21 13:53
Hi,
I've tried the full reindexing (bibindex -R) previously (on test environment), but it seems not to have fix the problem. For the 2. point, while i'm trying to run inveniocfg i'm getting this error:

(b2share) # ./inveniocfg --detect-system-details
working outside of application context

@nharraud i'll send you link to document by mail, and more detailed error message.
Here are some information from db encodings:

mysql> show variables like 'char%';
+--------------------------+----------------------------+
| Variable_name            | Value                      |
+--------------------------+----------------------------+
| character_set_client     | latin1                     |
| character_set_connection | latin1                     |
| character_set_database   | latin1                     |
| character_set_filesystem | binary                     |
| character_set_results    | latin1                     |
| character_set_server     | latin1                     |
| character_set_system     | utf8                       |
| character_sets_dir       | /usr/share/mysql/charsets/ |
+--------------------------+----------------------------+
8 rows in set (0.00 sec)

**Comment by nharraud** [comment] 2015-05-21 15:18
Thank you @llehtine. The database is encoded in latin1 and not utf8. I think this is why you are having these errors.
Here is what it looks like on my dev instance:
```
(b2share)[vagrant@localhost b2share]$  inveniomanage  database mysql-info
character_set_client: utf8
character_set_connection: utf8
character_set_database: utf8
character_set_results: utf8
character_set_server: latin1
character_set_system: utf8
collation_connection: utf8_general_ci
collation_database: utf8_general_ci
collation_server: latin1_swedish_ci
```
What matters are the database and the client connections, they should be in UTF-8.

**Comment by llehtine** [comment] 2015-05-22 07:21
Hi,
with inveniomanage-command i'm getting this:

(b2share)[root@test-eudatis invenio.base-instance]# inveniomanage database mysql-info
version: 5.1.73
character_set_client: utf8
character_set_connection: utf8
character_set_database: utf8
character_set_results: utf8
character_set_server: latin1
character_set_system: utf8
collation_connection: utf8_general_ci
collation_database: utf8_general_ci
collation_server: latin1_swedish_ci

**Comment by nharraud** [comment] 2015-05-22 08:41
Ok thanks @llehtine, maybe you called  `show variables like 'char%';` without specifying the database. I did it too the first time and saw different results.
So still no luck with this bug then. I will try to debug it as soon as I get the document causing it.

**Comment by tiborsimko** [comment] 2015-05-22 16:03
> I've tried the full reindexing (bibindex -R) previously (on test environment), but it seems not to have fix the problem.

Do you mean that the reindexing *also* generated the same integrity check error?  That would be surprising, since there are only ~200 records on B2SHARE, while the indexer flushing frequency is set to a much higher default value.  (Meaning that the indexer manages to build the whole forward/reverse index entries in memory before committing them to the database; so there should be no UPDATE statement to existing entries to perform, only INSERT statements for newly build entries, so to speak, when reindexing.) Anyway, I understood you'll post more logs and details to @nharraud, so we can have a closer look then.

**Comment by llehtine** [comment] 2015-07-07 11:41
#652 solved problem that new entries weren't found on search. While it was running, there was still bunch of errors about the duplicate entries coming to log files and author-strings were still quite long: https://b2share.eudat.eu/search?p=author%3A%22Bridget+Almas%2C+Juan+Bicarregui%2C+Alan+Blatecky%2C+Sean+Hill%2C+Larry+Lannom%2C+Rob+Pennington%2C+Rainer+Stotzka%2C+Andrew+Treloar%2C+Ross+Wilkinson%2C+Peter+Wittenburg%2C+Zhu+Yunqiang%22

**Comment by emanueldima** [comment] 2017-01-10 14:40
won't fix in v1, N/A in v2

**Closed by emanueldima** 2017-01-10 14:40 UTC
