### ISSUE TITLE
interface: edit record add button does not work properly

### ISSUE THREAD

**Issue by hevp** [EUDAT-B2SHARE/b2share#1450] opened 2017-04-12 14:06 UTC
When editing an existing published record, pressing the 'Add' buttons below all schema elements do not show any interface changes, i.e. no new text fields show up.

Upon submit, the interface shows that the actual fields were added in the data structure (by presumably javascript?):

`Please provide a correct value for field: creators/2/creator_name`

`Please provide a correct value for field: creators/3/creator_name`

`Please provide a correct value for field: creators/4/creator_name`

`Please provide a correct value for field: creators/5/creator_name`

`Please provide a correct value for field: creators/6/creator_name`

**Comment by hevp** [comment] 2017-04-12 14:10
![screen shot 2017-04-12 at 16 09 38](https://cloud.githubusercontent.com/assets/4790568/24961880/79f786a6-1f9a-11e7-8a9a-055107c27bf0.png)

**Comment by emanueldima** [comment] 2017-04-13 07:32
duplicate of https://github.com/EUDAT-B2SHARE/b2share/issues/1425

**Closed by emanueldima** 2017-04-13 07:32 UTC
