### ISSUE TITLE
Metadata exports do not work

### ISSUE THREAD

**Issue by chStaiger** [EUDAT-B2SHARE/b2share#539] opened 2015-01-15 08:05 UTC
- The export metadata links Bibtex, and MARC do not seem to work. When clicked they point again to the landing page/record.

- The export links EndNote, NLM, and RefWorks only export dublin core not the full metadata e.g. for record https://b2share.eudat.eu/record/125 the community-defined metadata is not exported.

**Comment by emanueldima** [comment] 2015-07-20 08:10
- [ ] Export Bibtex metadata link
- [ ] Export MARC metadata link
- [ ] Export community metadata to EndNote
- [ ] Export community metadata to NLM
- [ ] Export community metadata to RefWorks

**Comment by emanueldima** [comment] 2015-07-20 09:59
I'm no expert in the various metadata formats, but I found that EndNote, NLM and RefWorks have, as bibliographic formats, pretty strict schemas, and do not have equivalents for our community specific metadata fields. The documentation is also lacking. @chStaiger can you help with specific examples or docs?

**Comment by cjhak** [comment] 2015-07-21 13:22
@chStaiger Do you know of any actual EUDAT use cases for the EndNote, NLM and RefWorks formats? I'm inclined to cease supporting export for these formats in B2SHARE. Is there really any need for them?

**Comment by cjhak** [comment] 2015-08-27 10:53
@emanueldima, @llehtine Re-opening this issue: bibtex exports does not seem to work on test-eudatis, but it works in my dev env. Can anyone of you figure out what the problem is?

**Comment by llehtine** [comment] 2015-08-27 11:35
error logs have this:
2015-08-27 14:34:19,226 ERROR:  [in /var/www/.virtualenvs/b2share/lib/python2.7/site-packages/invenio-2.0.6.dev20150717-py2.7.egg/invenio/ext/logging/wrappers.py:310]
Traceback (most recent call last):
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/invenio-2.0.6.dev20150717-py2.7.egg/invenio/modules/formatter/engine.py", line 870, in eval_format_element
    output_text = function(**params)
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/invenio-2.0.6.dev20150717-py2.7.egg/invenio/modules/formatter/format_elements/bfe_bibtex.py", line 294, in format_element
    month = get_month(bfo.field("269__c"))
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/invenio-2.0.6.dev20150717-py2.7.egg/invenio/modules/formatter/format_elements/bfe_bibtex.py", line 502, in get_month
    for x in language_list_long()]
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/invenio-2.0.6.dev20150717-py2.7.egg/invenio/base/i18n.py", line 113, in language_list_long
    CFG_SITE_LANGS)
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/invenio-2.0.6.dev20150717-py2.7.egg/invenio/base/i18n.py", line 112, in <lambda>
    return map(lambda ln: [ln, babel.Locale.parse(ln).get_language_name()],
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/babel/core.py", line 313, in parse
    raise UnknownLocaleError(input_id)
UnknownLocaleError: unknown locale 'e'
2015-08-27 14:34:19,233 ERROR: Error when evaluating format element BFE_BIBTEX with parameters {'width': '80', 'bfo': <invenio.modules.formatter.engine.BibFormatObject object at 0x7f6d97f4f410>}. [in /var/www/.virtualenvs/b2share/lib/python2.7/site-packages/invenio-2.0.6.dev20150717-py2.7.egg/invenio/modules/formatter/engine.py:890]
Traceback (most recent call last):
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/invenio-2.0.6.dev20150717-py2.7.egg/invenio/modules/formatter/engine.py", line 878, in eval_format_element
    x_name=name, x_params=str(params)))
InvenioBibFormatError: Error when evaluating format element BFE_BIBTEX with parameters {'width': '80', 'bfo': <invenio.modules.formatter.engine.BibFormatObject object at 0x7f6d97f4f410>}.

**Comment by cjhak** [comment] 2015-09-02 03:44
Still an issue, moving to 1.6.1.

**Comment by emanueldima** [comment] 2015-09-14 06:52
@llehtine There seems to be a configuration error in `invenio.cfg`. The line:
````
CFG_SITE_LANGS = u'en'
````

should be:

````
CFG_SITE_LANGS = [u'en']
````

**Comment by llehtine** [comment] 2015-09-14 12:52
Hi,

After changing variables, it seems that the bibtex metadata problem is fixed. I've now changed variables on test/prod/training. Closing the issue.

**Closed by llehtine** 2015-09-14 12:52 UTC
Labels: Bug, Deployment
