### ISSUE TITLE
AAI integration

### ISSUE THREAD

**Issue by stranak** [EUDAT-B2SHARE/b2share#147] opened 2014-02-17 10:39 UTC
Invenio native functionality should be ready.

**Comment by emanueldima** [comment] 2015-05-18 07:07
Closing this one as a duplicate of https://github.com/EUDAT-B2SHARE/b2share/issues/123, https://github.com/EUDAT-B2SHARE/b2share/issues/474 and https://github.com/EUDAT-B2SHARE/b2share/issues/530

**Closed by emanueldima** 2015-05-18 07:07 UTC
Labels: Duplicate, Enhancement, Important
