### ISSUE TITLE
Gnuplot-py-1.8 cannot be installed from sourceforge (site offline)

### ISSUE THREAD

**Issue by dblommesteijn** [EUDAT-B2SHARE/b2share#564] opened 2015-02-10 17:16 UTC
Sourceforge.net is in offline mode, therefore we cannot install the `gnuplot-py-1.8` dependency in `requirements-extras.txt`, and Travis builds are failing.

I suspect all `sourceforge` dependencies are failing right now.

![screen shot 2015-02-10 at 18 15 34](https://cloud.githubusercontent.com/assets/395001/6132125/d57a6576-b150-11e4-93d2-28a6e8b2b8de.png)

**Comment by emanueldima** [comment] 2015-02-11 11:19
I think the offline mode was temporary and the issue is now solved (see the current Travis builds for e.g. https://github.com/EUDAT-B2SHARE/b2share/pull/565). I don't see how we could protect against that, anyway.

**Comment by dblommesteijn** [comment] 2015-02-11 11:21
Reducing the amount of third-party mirrors could be an option.

**Comment by emanueldima** [comment] 2015-05-04 09:20
I personally don't know how to fix this issue in a general way. Invenio2 already adds different requirement profiles. Won't fix?

**Comment by cjhak** [comment] 2015-05-04 13:18
I remove it from the milestone but leave it open (as in postponed indefinitely) for now.

**Closed** 2015-12-01 10:54 UTC
Labels: Bug
