### ISSUE TITLE
fix issues signalled in PR 1228

### ISSUE THREAD

**Issue by emanueldima** [EUDAT-B2SHARE/b2share#1236] opened 2016-12-15 14:27 UTC
1. [ ] replace ePIC_PID with just 'ePIC'
2. [ ] avoid using 'DOI_RESERVED' as pid_type (use internal invenio pid status)
3. [ ] move `_pid` content to `alternate_identifier`
4. [ ] use epic pid as record identifier for oai-pmh, not the b2rec id

**Comment by nharraud** [comment] 2016-12-15 14:42
duplicate of #1235

**Closed by nharraud** 2016-12-15 14:42 UTC
Labels: Important
