### ISSUE TITLE
community_specific member missing in new drafts

### ISSUE THREAD

**Issue by janiheikkinen** [EUDAT-B2SHARE/b2share#1587] opened 2017-11-27 07:49 UTC
Has there been a behavioural/structural change in creating community specific metadata element for new drafts (affecting the jsonpatch path, in v2.1.0)? So far the patch path has followed form /community_specific/<id>/<field>". This is not clearly defined in the current API documentation (https://eudat-b2share-test.csc.fi/help/api). 

Assuming there is a draft created previously through UI with all community specific metadata fields empty, when issuing a request as follows:
curl -k -X PATCH -H 'Content-Type:application/json-patch+json' -d '[{"op": "add", "path": "/community_specific/cee77dd0-9149-4a7b-9c28-85a8f7052bd9/instrument", "value": "EISCAT Svalbard IS Radar Longyearbyen"}, {"op": "add", "path": "/community_specific/cee77dd0-9149-4a7b-9c28-85a8f7052bd9/start_time", "value": "2013-10-22 14:00:12 UT"}, {"op": "add", "path": "/community_specific/cee77dd0-9149-4a7b-9c28-85a8f7052bd9/end_time", "value": "2013-10-22 15:59:53 UT"}, {"op": "add", "path": "/community_specific/cee77dd0-9149-4a7b-9c28-85a8f7052bd9/status", "value": "Final"}, {"op": "add", "path": "/community_specific/cee77dd0-9149-4a7b-9c28-85a8f7052bd9/latitude", "value": "78.09"}, {"op": "add", "path": "/community_specific/cee77dd0-9149-4a7b-9c28-85a8f7052bd9/longitude", "value": "16.02"}, {"op": "add", "path": "/community_specific/cee77dd0-9149-4a7b-9c28-85a8f7052bd9/altitude", "value": "0.434"}]' https://eudat-b2share-test.csc.fi/api/records/21bec7d88e5441bd9966c4e0efdc4f64/draft?access_token=<token>;

The test server log:
[2017-11-25 15:55:55,346] ERROR in app: Exception on /records/21bec7d88e5441bd9966c4e0efdc4f64/draft [PATCH]
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/jsonpointer.py", line 231, in walk
    return doc[part]
KeyError: 'community_specific'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib64/python3.4/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib64/python3.4/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib64/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/lib64/python3.4/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib64/python3.4/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib64/python3.4/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/invenio_rest/views.py", line 215, in dispatch_request
    *args, **kwargs
  File "/usr/lib64/python3.4/site-packages/flask/views.py", line 149, in dispatch_request
    return meth(*args, **kwargs)
  File "./b2share/modules/deposit/views.py", line 175, in patch
    result = super(DepositResource, self).patch(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/invenio_rest/decorators.py", line 48, in inner
    return f(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/invenio_records_rest/views.py", line 296, in inner
    return f(self, pid=pid, record=record, *args, **kwargs)
  File "/usr/lib/python3.4/site-packages/invenio_records_rest/views.py", line 339, in need_record_permission_decorator
    verify_record_permission(permission_factory, record)
  File "/usr/lib/python3.4/site-packages/invenio_records_rest/views.py", line 314, in verify_record_permission
    if not permission_factory(record=record).can():
  File "./b2share/modules/deposit/permissions.py", line 197, in __init__
    self._load_additional_permissions()
  File "./b2share/modules/deposit/permissions.py", line 270, in _load_additional_permissions
    apply_patch(new_deposit, patch, in_place=True)
  File "/usr/lib/python3.4/site-packages/jsonpatch.py", line 151, in apply_patch
    return patch.apply(doc, in_place)
  File "/usr/lib/python3.4/site-packages/jsonpatch.py", line 349, in apply
    obj = operation.apply(obj)
  File "/usr/lib/python3.4/site-packages/jsonpatch.py", line 417, in apply
    subobj, part = self.pointer.to_last(obj)
  File "/usr/lib/python3.4/site-packages/jsonpointer.py", line 158, in to_last
    doc = self.walk(doc, part)
  File "/usr/lib/python3.4/site-packages/jsonpointer.py", line 234, in walk
    raise JsonPointerException("member '%s' not found in %s" % (part, doc))
jsonpointer.JsonPointerException: member 'community_specific' not found in {'_pid': [{'type': 'vb2rec', 'value': '75182f7d206845809893d19d6fa4869c'}], 'publication_state': 'draft', 'titles': [{'title': 'test'}], 'community': 'b344f92a-cd0e-4e4c-aa09-28b5f95f7e41', 'open_access': True, '$schema': 'https://eudat-b2share-test.csc.fi/api/communities/b344f92a-cd0e-4e4c-aa09-28b5f95f7e41/schemas/0#/draft_json_schema', '_deposit': {'id': '21bec7d88e5441bd9966c4e0efdc4f64', 'created_by': 590, 'owners': [590], 'status': 'draft'}}

However, if a draft is created (through UI) with even one community specific metadata field, the community_specific and corresponding id exists.

Should client create the community_specific element through the API if there is no such? Is it allowed to do that? If so, how the community_specific id is defined (so far it has remained static for the same community)?

**Comment by emanueldima** [comment] 2017-11-27 08:33
The test server has been upgraded last week with a 2.1.0 release candidate, so maybe a bug in this version is causing your problems. I'll try to replicate the issue.

**Comment by emanueldima** [comment] 2017-11-27 10:52
Ok, right after the creation of the draft there is a `community_specific` empty object. Through patching it's not possible to add a `/community_specific/cee77dd0-9149-4a7b-9c28-85a8f7052bd9/instrument` value, because `cee77dd0-9149-4a7b-9c28-85a8f7052bd9` doesn't yet exist. The error message is currently obviously bad, but to make it work for now you should first create this empty object and then add the entries inside it, like in the call below (see the first op):

````
curl -k -X PATCH -H 'Content-Type:application/json-patch+json' 
-d '[
  {"op": "add", "path": "/community_specific/cee77dd0-9149-4a7b-9c28-85a8f7052bd9", "value": {}}, 
  {"op": "add", "path": "/community_specific/cee77dd0-9149-4a7b-9c28-85a8f7052bd9/instrument", "value": "EISCAT Svalbard IS Radar Longyearbyen"}, 
  ...
]' https://eudat-b2share-test.csc.fi/api/records/21bec7d88e5441bd9966c4e0efdc4f64/draft?access_token=...
````

This should be the behaviour for all b2share versions and I tested that it works for the Clarin community (I cannot test it with EISCAT, but the behaviour should be the same).

**Comment by emanueldima** [comment] 2017-12-20 08:54
Closing as not a bug (just normal json behaviour). Please let me know if you disagree.

**Closed by emanueldima** 2017-12-20 08:54 UTC
