### ISSUE TITLE
Table for contents to B2Share Guide / B2Share faq drop down text

### ISSUE THREAD

**Issue by llehtine** [EUDAT-B2SHARE/b2share#883] opened 2016-03-17 14:00 UTC
B2Share guide should have table of contents, so it would be easy to just click what part of the guide you want to see instead of scrolling all the way back down. 

Also the B2Share FAQ should have drop down text, where you could click on question and after that it would show the answer-part

**Comment by emanueldima** [comment] 2016-03-17 14:05
duplicate of https://github.com/EUDAT-B2SHARE/b2share/issues/871

**Comment by hevp** [comment] 2019-02-12 16:39
Both documents are no longer part of the software repository.

Equivalents for the B2SHARE user guide can be found here:
- FAQ: https://eudat.eu/services/userdoc/b2share
- User guide: https://eudat.eu/services/userdoc/b2share-usage

**Closed by hevp** 2019-02-12 16:39 UTC
Labels: Docs, Feature
