### ISSUE TITLE
UI: record edit loading indefinitely

### ISSUE THREAD

**Issue by nharraud** [EUDAT-B2SHARE/b2share#1197] opened 2016-11-15 12:00 UTC
**Problem:**
While on the record edit page `https://<HOST>/records/<RECID>/edit`, when the page is reloaded, sometime the page just displays "loading..." and never shows the record.
This error happens randomly but seems to not occur when the cache is disabled. When the error occurs the console just displays:
```
--- ajaxGet: 127 /api/users/current undefined
ajax.js:14 --- ajaxGet: 150 /api/records/fdd070cd42dc4ce1909e21bf0abe24b6/draft undefined
ajax.js:158   > ajaxRet: 446 /api/users/current Object {data: Object, link: null, etag: null}
ajax.js:165   > ajaxRet: 457 not modified /api/records/fdd070cd42dc4ce1909e21bf0abe24b6/draft
```
Note that the numbers after `ajaxRet:` change each time so they don't seem to be relevant.

**Comment by emanueldima** [comment] 2016-11-28 17:02
I can't reproduce this bug, it could be a race condition. Any hints on what can trigger it? Is there anything else in the console output?

**Comment by emanueldima** [comment] 2016-12-23 06:57
closing as I can't reproduce it, please reopen if necessary

**Closed by emanueldima** 2016-12-23 06:57 UTC
Labels: Bug, Important, UI
